package com.demo.entities;
// Generated Feb 24, 2024, 2:34:54 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;


/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "bill", catalog = "managementhotel")
public class Bill implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Payment payment;
	private String service;
	private Date checkInFrom;
	private Date checkInUntil;
	private Date checkOutFrom;
	private Date checkOutUntil;
	private String mainGuest;
	private String status;
	private String name;
	private String email;
	private String phone;
	private String note;
	private String securityCode;
	private Double total;
	private Set<BillDetail> billDetails = new HashSet<BillDetail>(0);

	public Bill() {
	}

	public Bill(Payment payment) {
		this.payment = payment;
	}

	public Bill(Account account, Payment payment, String service, Date checkInFrom, Date checkInUntil,
			Date checkOutFrom, Date checkOutUntil, String mainGuest, String status, String name, String email,
			String phone, String note, String securityCode, Double total, Set<BillDetail> billDetails) {
		this.account = account;
		this.payment = payment;
		this.service = service;
		this.checkInFrom = checkInFrom;
		this.checkInUntil = checkInUntil;
		this.checkOutFrom = checkOutFrom;
		this.checkOutUntil = checkOutUntil;
		this.mainGuest = mainGuest;
		this.status = status;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.note = note;
		this.securityCode = securityCode;
		this.total = total;
		this.billDetails = billDetails;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSender")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_payment", nullable = false)
	public Payment getPayment() {
		return this.payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}

	@Column(name = "service", length = 65535)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_in_from", length = 10)
	public Date getCheckInFrom() {
		return this.checkInFrom;
	}

	public void setCheckInFrom(Date checkInFrom) {
		this.checkInFrom = checkInFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_in_until", length = 10)
	public Date getCheckInUntil() {
		return this.checkInUntil;
	}

	public void setCheckInUntil(Date checkInUntil) {
		this.checkInUntil = checkInUntil;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_out_from", length = 10)
	public Date getCheckOutFrom() {
		return this.checkOutFrom;
	}

	public void setCheckOutFrom(Date checkOutFrom) {
		this.checkOutFrom = checkOutFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_out_until", length = 10)
	public Date getCheckOutUntil() {
		return this.checkOutUntil;
	}

	public void setCheckOutUntil(Date checkOutUntil) {
		this.checkOutUntil = checkOutUntil;
	}

	@Column(name = "main_guest", length = 250)
	public String getMainGuest() {
		return this.mainGuest;
	}

	public void setMainGuest(String mainGuest) {
		this.mainGuest = mainGuest;
	}

	@Column(name = "status", length = 250)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 250)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "security_code", length = 250)
	public String getSecurityCode() {
		return this.securityCode;
	}

	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode;
	}

	@Column(name = "total", precision = 22, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bill")
	public Set<BillDetail> getBillDetails() {
		return this.billDetails;
	}

	public void setBillDetails(Set<BillDetail> billDetails) {
		this.billDetails = billDetails;
	}

}
