package com.demo.entities;
// Generated Feb 24, 2024, 2:34:54 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Categoryimage generated by hbm2java
 */
@Entity
@Table(name = "categoryimage", catalog = "managementhotel")
public class Categoryimage implements java.io.Serializable {

	private Integer id;
	private Hotel hotel;
	private String name;
	private Set<Image> images = new HashSet<Image>(0);

	public Categoryimage() {
	}

	public Categoryimage(Hotel hotel, String name) {
		this.hotel = hotel;
		this.name = name;
	}

	public Categoryimage(Hotel hotel, String name, Set<Image> images) {
		this.hotel = hotel;
		this.name = name;
		this.images = images;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idHotel", nullable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoryimage")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

}
