package com.demo.entities;
// Generated Feb 24, 2024, 2:34:54 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;

import jakarta.persistence.*;


/**
 * Complain generated by hbm2java
 */
@Entity
@Table(name = "complain", catalog = "managementhotel")
public class Complain implements java.io.Serializable {

	private Integer id;
	private Account accountBySender;
	private Account accountByHandler;
	private Date dateSent;
	private Date settlementDate;
	private String title;
	private String content;
	private Boolean status;

	public Complain() {
	}

	public Complain(Account accountBySender) {
		this.accountBySender = accountBySender;
	}

	public Complain(Account accountBySender, Account accountByHandler, Date dateSent, Date settlementDate, String title,
			String content, Boolean status) {
		this.accountBySender = accountBySender;
		this.accountByHandler = accountByHandler;
		this.dateSent = dateSent;
		this.settlementDate = settlementDate;
		this.title = title;
		this.content = content;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender", nullable = false)
	public Account getAccountBySender() {
		return this.accountBySender;
	}

	public void setAccountBySender(Account accountBySender) {
		this.accountBySender = accountBySender;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "handler")
	public Account getAccountByHandler() {
		return this.accountByHandler;
	}

	public void setAccountByHandler(Account accountByHandler) {
		this.accountByHandler = accountByHandler;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_sent", length = 10)
	public Date getDateSent() {
		return this.dateSent;
	}

	public void setDateSent(Date dateSent) {
		this.dateSent = dateSent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "settlement_date", length = 10)
	public Date getSettlementDate() {
		return this.settlementDate;
	}

	public void setSettlementDate(Date settlementDate) {
		this.settlementDate = settlementDate;
	}

	@Column(name = "title", length = 250)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
