package com.demo.entities;
// Generated Feb 25, 2024, 2:30:44 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * ImagePapers generated by hbm2java
 */
@Entity
@Table(name = "image_papers", catalog = "managementhotel")
public class ImagePapers implements java.io.Serializable {

	private Integer id;
	private Hotel hotel;
	private String name;

	public ImagePapers() {
	}

	public ImagePapers(Hotel hotel, String name) {
		this.hotel = hotel;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idHotel", nullable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
