package com.demo.entities;
// Generated Feb 25, 2024, 2:30:44 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "managementhotel")
public class Image implements java.io.Serializable {

	private Integer id;
	private Categoryimage categoryimage;
	private String name;

	public Image() {
	}

	public Image(Categoryimage categoryimage) {
		this.categoryimage = categoryimage;
	}

	public Image(Categoryimage categoryimage, String name) {
		this.categoryimage = categoryimage;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCategoryImage", nullable = false)
	public Categoryimage getCategoryimage() {
		return this.categoryimage;
	}

	public void setCategoryimage(Categoryimage categoryimage) {
		this.categoryimage = categoryimage;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
