package com.demo.entities;
// Generated Feb 24, 2024, 2:34:54 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;


/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room", catalog = "managementhotel")
public class Room implements java.io.Serializable {

	private Integer id;
	private Hotel hotel;
	private String name;
	private Boolean status;
	private Double price;
	private Double priceDiscount;
	private String reasonDiscount;
	private Integer roomMax;
	private Integer roomNow;
	private Integer peopleMin;
	private Integer peopleMax;
	private String describes;
	private Set<BillDetail> billDetails = new HashSet<BillDetail>(0);

	public Room() {
	}

	public Room(Hotel hotel) {
		this.hotel = hotel;
	}

	public Room(Hotel hotel, String name, Boolean status, Double price, Double priceDiscount, String reasonDiscount,
			Integer roomMax, Integer roomNow, Integer peopleMin, Integer peopleMax, String describes,
			Set<BillDetail> billDetails) {
		this.hotel = hotel;
		this.name = name;
		this.status = status;
		this.price = price;
		this.priceDiscount = priceDiscount;
		this.reasonDiscount = reasonDiscount;
		this.roomMax = roomMax;
		this.roomNow = roomNow;
		this.peopleMin = peopleMin;
		this.peopleMax = peopleMax;
		this.describes = describes;
		this.billDetails = billDetails;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idHotel", nullable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "price_discount", precision = 22, scale = 0)
	public Double getPriceDiscount() {
		return this.priceDiscount;
	}

	public void setPriceDiscount(Double priceDiscount) {
		this.priceDiscount = priceDiscount;
	}

	@Column(name = "reason_discount", length = 250)
	public String getReasonDiscount() {
		return this.reasonDiscount;
	}

	public void setReasonDiscount(String reasonDiscount) {
		this.reasonDiscount = reasonDiscount;
	}

	@Column(name = "room_max")
	public Integer getRoomMax() {
		return this.roomMax;
	}

	public void setRoomMax(Integer roomMax) {
		this.roomMax = roomMax;
	}

	@Column(name = "room_now")
	public Integer getRoomNow() {
		return this.roomNow;
	}

	public void setRoomNow(Integer roomNow) {
		this.roomNow = roomNow;
	}

	@Column(name = "people_min")
	public Integer getPeopleMin() {
		return this.peopleMin;
	}

	public void setPeopleMin(Integer peopleMin) {
		this.peopleMin = peopleMin;
	}

	@Column(name = "people_max")
	public Integer getPeopleMax() {
		return this.peopleMax;
	}

	public void setPeopleMax(Integer peopleMax) {
		this.peopleMax = peopleMax;
	}

	@Column(name = "describes", length = 65535)
	public String getDescribes() {
		return this.describes;
	}

	public void setDescribes(String describes) {
		this.describes = describes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	public Set<BillDetail> getBillDetails() {
		return this.billDetails;
	}

	public void setBillDetails(Set<BillDetail> billDetails) {
		this.billDetails = billDetails;
	}

}
